name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Libowfat
      run: wget http://www.fefe.de/libowfat/libowfat-0.34.tar.xz
    - name: uncopmpress
      run: tar -xf libowfat-0.34.tar.xz
    - name: rename
      run: mv libowfat-0.34 libowfat
    - name: go to libowfat
      run: cd libowfat
    - name: build libowfat
      run: make
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
